- src/student_success_tool/analysis/pdp/features/student.py
- tests/analysis/pdp/features/test_student.py
- renames feature/func, `diff_gpa_year_1_to_term_1` => `diff_gpa_term_1_to_year_1`
- autoformatting applied on save... i wonder why the lint check didn't trigger on that before!
Prior work: PR #7 
As discussed here: https://github.com/datakind/student-success-tool/pull/7#discussion_r1809670692
> Rename gpa diff func/feature

- src/student_success_tool/analysis/pdp/features/cumulative.py
- tests/analysis/pdp/features/test_cumulative.py
- Adds unit tests for various cumulative feature funcs, which I had left as a high-risk TODO in the code 😇 
- Explicitly sets a couple dtypes in the cumulative features code, but effectively cosmetic
Follows PR #20 
Nope! Just tests.
> [PDP] Add unit tests for cumulative features

- pyproject.toml
- uv.lock
> build: Bump seaborn and shap pkgs

- .github/actions/setup-python-env/action.yml
- pyproject.toml
- uv.lock
That's it!
Just keeping our tools up to date...
> build: Bump ruff and uv tools

- src/student_success_tool/analysis/pdp/features/cumulative.py
- src/student_success_tool/analysis/pdp/features/student_term.py
- src/student_success_tool/analysis/pdp/targets/failure_to_retain.py
- src/student_success_tool/analysis/pdp/targets/shared.py
- tests/analysis/pdp/features/test_cumulative.py
- tests/analysis/pdp/features/test_student_term.py
- tests/analysis/pdp/targets/test_shared.py
- adds "term is pre-cohort" feature, and leverages it to improve/streamline pre-cohort term filtering when making a labeled dataset
- adds "num courses in study area" features, both student-term-level and as cumulative fractions
"Pre-cohort" terms came up as a data quality issue for a school, to be filtered out. But it was suggested that we make a feature to note their existence, in case students with pre-cohort terms are meaningfully different (wrt outcome) from those without. This also adds a long-standing feature want, related to the number of courses in students' stated program of study area.
Follows behind PR #38 
- do these features make sense?
- any other notable features we might want to add?
> [pdp] Add some new features

- src/student_success_tool/analysis/pdp/dataops.py
- src/student_success_tool/analysis/pdp/utils.py
This was a bug! Data generated via lib func could have different names compared to the same data read back from a delta table. Folks have run into this in multiple PDP pipelines.
- is this an acceptable way to handle the problem? bit of a hack, but 🤷
> [pdp] Lowercase all pdp feature names

- notebooks/pdp/03-train-evaluate-model-TEMPLATE.py
Updates template train-evaluate-model nb using code in this repo in a way that's compatible with AutoML -- the key was installing `sst` without its dependencies, and instead leveraging those already available in the Databricks Runtime. This is a bit of a hack, but it works, and is closer to what Databricks recommends for AutoML usage.
It also leverages the new project config functionality. The interface is a bit rough right now, but I'll make it better in a next version.
https://datakind.slack.com/archives/C07DWDMN8SW/p1734287236261779
Does this seem good to you as a first iteration? It should look familiar (similar to the private repo's AutoML nb), if a bit clunky -- I'm going to change and improve functionality later, in separate work.
> [pdp] Update template modeling nb to work

- src/student_success_tool/modeling/feature_selection.py
https://datakind.slack.com/archives/C07RJHJU59D/p1736294888283089
> [pdp] Make collinear feature selection optional

- src/student_success_tool/modeling/inference.py
- tests/modeling/test_inference.py
- changes output data structure from "long" to "wide", features-wise
- adds optional logic to compute "support needed" bool values from probs
- updates unit tests, including a little bit for new float rounding
Cousin PR: https://github.com/datakind/student-success-intervention/pull/127
This is similar to but different from what you implemented in the other repo. My intention is that this replaces that in the near future. Do you have any concerns about the differences?
> Update inference output file per discussion

- src/student_success_tool/modeling/utils.py
- tests/modeling/test_utils.py
- removes unnecessary error handling
- simplifies test assertion
- autoformats code+tests
minor follow-up to PR #58
> [pdp] Tidy load features code

- CHANGELOG.md
- pyproject.toml
- sets package version to v0.1.1: it's _mostly_ compatible with v0.1.0, and this is still early days, so no need to bump to v0.2.0 until notable breaking changes occur
- adds changelog for this new version
we're due for a version bump
- are there any reasons _not_ to cut this release?
> Prepare v0.1.1 release changelog

- src/student_success_tool/pipeline_utils/plot.py
This change creates a new file in pipeline utils to plot a beeswarm chart.
The summary_plot method of generating charts for shap data is deprecated.
> Created a utility function to generate a shap beeswarm plot

- .github/workflows/style.yml
- .github/workflows/type-check.yml
- src/student_success_tool/modeling/training.py
one of our github actions has been compromised: https://www.stepsecurity.io/blog/harden-runner-detection-tj-actions-changed-files-action-is-compromised
> ci: remove compromised action from workflows

- src/student_success_tool/assets/pdp/features_table.toml
- src/student_success_tool/modeling/inference.py
- tests/modeling/test_inference.py
- adds a couple missing feature table mappings for 0-level courses
- adds function to more flexibly match feature columns to human-friendly names, falling back to _regular expressions_ in case a perfect match is not found
- adds entries to features table that leverage regex patterns; if confused, check out the test cases
We sent out the first PDP predictions, and the client had some specific questions about feature meanings that these changes would have addressed.
https://datakind.slack.com/archives/C07BL3H5E4Q/p1741888821264579
> [pdp] improve coverage+matching for human-friendly feature names

- .github/actions/setup-python-env/action.yml
- .github/workflows/pre-release.yml
fast-follow to https://github.com/datakind/student-success-tool/pull/106
> Further lock down actions

- pipelines/institution_id/00-data-assessment-TEMPLATE.py
Updating EDA notebook 
- added code to see how many students filtered out due to missing course identifiers are transfers vs. non-transfers
- added code to see how many students remain after we filter the above ^ out
- filtering cohort data as well for consistency with course_filtered dataset
- plotting first year GPA by enrollment type and credential type sought to evaluate if these types should be included in same or different models based on differences
- adding code for computing and plotting average and median values for percent credits earned over years (1-4)
- Adding a student-demographics section with some more detailed plots
Anything you guys would like to change?
> adding to EDA notebook

- pipelines/institution_id/01-preprocess-data-TEMPLATE.py
- pipelines/institution_id/02-train-model-TEMPLATE.py
- pipelines/institution_id/03-make-predictions-TEMPLATE.py
bring (mostly) train-model template nb into line with current (develop) version of the sst src code
APIs / functionality has changed since the template nb was last updated
> [pdp] update template nbs

- pipelines/institution_id/config-TEMPLATE.toml
- follows naming convention for datasets and models
- adds more commonly used fields, even if commented out
- fills in placeholder values with slightly more realistic values
there's been some confusion about how to translate this template into an actual project config; these changes are meant to make things more clear and closer to "standard"
- anything you don't like here?
- anything you would like included here?
> [pdp] update project config template

- pipelines/institution_id/02-train-model-TEMPLATE.py
- pipelines/institution_id/config-TEMPLATE.toml
- src/student_success_tool/modeling/evaluation.py
- src/student_success_tool/schemas/pdp/project.py
- tests/modeling/test_evaluation.py
- adds "evaluation" block to project config, and puts a single parameter in it; not very useful rn, but could be in the future, and at the very least gets rid of a "magic" number in the training model nb
- improves dataset block in template project config; this is kind of unrelated, but it snuck in (sorry)
- adds function to compute many classification model evaluation metrics; should be used to simplify the eval loop in model training nb
- splits feature permutation importance into two functions: one to compute the importances, and the other to plot them; this gives people more control
- renames / reorders various evaluation plotting functions, for consistency
**out-of-scope:** i didn't update the training model nb, because Vish is currently in that space still making changes for bias …
> [pdp] improve model evaluation code

- README.md
title says it all
https://app.asana.com/1/6325821815997/project/1207781048453811/task/1209881760767970?focus=true
- is anything unclear?
- have i forgotten anything?
> docs: add package release instructions

- pipelines/institution_id/00-data-assessment-TEMPLATE.py
- better leverages cfg in data asessment nb
- fixes a couple minor bugs / old things
> [pdp] update data assessment nb template for v0.2

- src/student_success_tool/converters/pdp/__init__.py
- src/student_success_tool/converters/pdp/raw_cohort.py
- src/student_success_tool/converters/pdp/raw_course.py
- tests/converters/pdp/test_raw_cohort.py
adds converter func to rename mangled column names in cohort dataset
feature request from school-specific PR: https://github.com/datakind/student-success-intervention/pull/160#discussion_r2035844679
> [pdp] add mangled column converter

- CHANGELOG.md
- pyproject.toml
- bumps pkg version to v0.2.0
- adds corresponding changelog entry
> Prepare v0.2.0 release

- README.md
- adds step-by-step instructions for modifying package dependencies
- adds quick hits for common development tasks
https://app.asana.com/1/6325821815997/project/1208486153653829/task/1209995775604437?focus=true
https://app.asana.com/1/6325821815997/project/1207781048453811/task/1209881760767970?focus=true
- can you follow these instructions on your own?
> add package management + development guides

- src/student_success_tool/modeling/evaluation.py
- Removed SLA plots and analysis from evaluation.
- We discussed as a team, and it appears that the team doesn't find it very useful for evaluating a model's performance.
- Did I miss anything? Looks like it's all covered in the evaluation file.
> removing sla plots from evaluation

- pipelines/institution_id/config-TEMPLATE.toml
- src/student_success_tool/schemas/pdp/project.py
- src/student_success_tool/selection/pdp.py
- src/student_success_tool/targets/pdp/credits_earned.py
- src/student_success_tool/targets/pdp/graduation.py
- src/student_success_tool/utils/misc.py
- src/student_success_tool/utils/types.py
- tests/schemas/pdp/test_project.py
- uv.lock
- separates selection and checkpoint configuration into their own sections under "preprocessing" in the project config, which aligns more closely with code structure and actual usage
- updates template project config and unit tests to match
- adds a new shared type for "intensity time limits" that is used across various parts of the code, including the updated project config
this is an awkward part of the code that i'd wanted to fix before v0.2.0, but it didn't get there in time
> [pdp] improve project config structure

- CHANGELOG.md
- pyproject.toml
Creating version 3.0 of SST. 
Check out CHANGELOG.md.
> bump latest package release for v0.3.0

- src/student_success_tool/configs/pdp.py
- tests/configs/test_pdp.py
Update the config class to accept the new dataset structure of bronze, silver, and gold tables
> Update datasets classes

- CHANGELOG.md
- pyproject.toml
Creating patch for latest dataset config with bronze/silver/gold dataset types.
> Create patch v0.3.1

- pipelines/institution_id/01-preprocess-data-TEMPLATE.py
- pipelines/institution_id/02-train-model-TEMPLATE.py
- pipelines/institution_id/03-make-predictions-TEMPLATE.py
changing typos in template notebooks 
- df_features --> df_labeled
- change in compute_feature_importance vs. plot_feature_importance code
- updating code for predict_proba
> making template changes as necessary

- CHANGELOG.md
- README.md
- pipelines/institution_id/00-data-assessment-TEMPLATE.py
- pipelines/institution_id/01-preprocess-data-TEMPLATE.py
- pipelines/institution_id/02-train-model-TEMPLATE.py
- pipelines/institution_id/03-make-predictions-TEMPLATE.py
- pipelines/institution_id/04-register-model-create-card-TEMPLATE.py
- pyproject.toml
> Add changelog and update versions

- pipelines/institution_id/03-make-predictions-TEMPLATE.py
- pipelines/tasks/pdp_model_inference/pdp_model_inference.py
- src/student_success_tool/modeling/inference.py
- Added training-phase tables for:
-- Support Score Distribution
-- SHAP Feature Importance
- Updated inference output to Include support scores alongside top-N SHAP features
Needed changes for Larry in the FE
No questions at this time
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1210616000866896
- https://app.asana.com/0/0/1210574582345354
> feat: added support scores to to features

- CHANGELOG.md
- pipelines/pdp/institution_id/00-data-assessment-TEMPLATE.py
- pipelines/pdp/institution_id/01-preprocess-data-TEMPLATE.py
- pipelines/pdp/institution_id/02-train-model-TEMPLATE.py
- pipelines/pdp/institution_id/03-make-predictions-TEMPLATE.py
- pipelines/pdp/institution_id/04-register-model-create-card-TEMPLATE.py
- pyproject.toml
- Fixed bug in features table (PR 229)
- Fixed bug in 12 credit features (PR 230)
> release 0.3.6

- CHANGELOG.md
- pipelines/custom/institution_id/02-train-model-TEMPLATE.py
- pipelines/custom/institution_id/03-make-predictions-TEMPLATE.py
- pipelines/custom/institution_id/04-register-model-create-card-TEMPLATE.py
- pipelines/custom/institution_id/05-inference-validation-TEMPLATE.py
- pipelines/pdp/institution_id/00-data-assessment-TEMPLATE.py
- pipelines/pdp/institution_id/01-preprocess-data-TEMPLATE.py
- pipelines/pdp/institution_id/02-train-model-TEMPLATE.py
- pipelines/pdp/institution_id/03-make-predictions-TEMPLATE.py
- pipelines/pdp/institution_id/04-register-model-create-card-TEMPLATE.py
- pyproject.toml
- Adjusted feature naming for better flexibility and robustness in feature table (PR 243)
- Updated codebased to have better data leakage handling (PR 237)
- Added SHAP feature metadata to FE tables to have better compatibility with FE needs and resolve endpoint bugs (PR 242)
- Updated model card output location to gold volumes instead of artifacts for compatibility with API endpoint & FE (PR 245)
> creating v0.3.7

- pipelines/pdp/institution_id/00-data-assessment-TEMPLATE.py
- pipelines/pdp/institution_id/01-preprocess-data-TEMPLATE.py
- pipelines/pdp/institution_id/02-train-model-TEMPLATE.py
- pipelines/pdp/institution_id/03-make-predictions-TEMPLATE.py
- pipelines/pdp/institution_id/04-register-model-create-card-TEMPLATE.py
1. remove "-TEMPLATE" when reading the config, I have to take it out anyway, unnecessary to have it as "-TEMPLATE" in the notebooks, we already know it's a template in the original file name and save it as just "config" when we clone it anyway
2. looking at how many students are lost in the filtered cohort df after dropping null course records + merging
3. drop re-admit category b/c I end up doing this for a lot of schools without re-admits to make the plots look cleaner
4. changing pct creds earned by year into an ax object b/c the percents weren't appropriately coming up otherwise
5. adding Y1 GPA / enrollment intensity plot
6. adding other small value counts I usually use
7. standardize and use filtered dfs for all plots 
8. adding course grades by delivery method plot
any oppositions …
> small template updates

- CHANGELOG.md
- pipelines/custom/institution_id/02-train-model-TEMPLATE.py
- pipelines/custom/institution_id/03-make-predictions-TEMPLATE.py
- pipelines/custom/institution_id/04-register-model-create-card-TEMPLATE.py
- pipelines/custom/institution_id/05-inference-validation-TEMPLATE.py
- pipelines/pdp/institution_id/00-data-assessment-TEMPLATE.py
- pipelines/pdp/institution_id/01-preprocess-data-TEMPLATE.py
- pipelines/pdp/institution_id/02-train-model-TEMPLATE.py
- pipelines/pdp/institution_id/03-make-predictions-TEMPLATE.py
- pipelines/pdp/institution_id/04-register-model-create-card-TEMPLATE.py
- pyproject.toml
- Created automated model selection (PR 267)
- Corrected aliasing in custom model cards (PR 264)
> creating v0.3.10
