src/student_success_tool/analysis/pdp/constants.py
I believe the default COVID academic years are off. Check my thinking here, but Spring 2020 is actually the academic year 2019-2020, and so on.
=> fix: covid academic years off

src/student_success_tool/analysis/pdp/README.md, src/student_success_tool/analysis/pdp/dataops.py, src/student_success_tool/analysis/pdp/features/shared.py, src/student_success_tool/analysis/pdp/features/student.py, src/student_success_tool/analysis/pdp/features/student_term.py, src/student_success_tool/analysis/pdp/schemas/base.py, src/student_success_tool/generation/pdp/raw_cohort.py, tests/analysis/pdp/features/test_course.py, tests/analysis/pdp/features/test_shared.py, tests/analysis/pdp/features/test_student.py, tests/analysis/pdp/features/test_student_term.py, tests/analysis/pdp/test_dataops.py
- removed hacky "num terms checkin" logic from student-term dataset functionality, and replaced it with a more general solution: a "cleanup" function applied to labeled data that dynamically nulls out values coming from years in the future (after the student-term used for prediction) to prevent data leakage
- as a result, included a few extra features that were previously dropped, including the fraction of credits earned year-by-year
- in order for new logic to work, renamed a few features to have a consistent "*_year_X" naming scheme
- also, added a parser to the base pdp cohort dataset schema that nullifies 0 values for "first year to *" fields, which are now included as features
- finally, fixed a bug in a couple CIP-based features that resulted in them being interpreted as numeric …
=> Improve handling for term/year features

src/student_success_tool/analysis/pdp/dataops.py, src/student_success_tool/analysis/pdp/features/course.py, src/student_success_tool/analysis/pdp/features/student_term.py, tests/analysis/pdp/features/test_course.py
- adds a course feature that computes a (categorical) grade value by converting numeric grades into classic "letter" grades
- replaces the raw grade with this categorical one where appropriate
This was the last piece needed to fully move away from assuming raw PDP grade values were categoricals. This _happened_ to be the case for HACC, and it also worked albeit differently for MSU, but the PDP spec specifically allows for numeric grades to take continuous values between 0.0 and 4.0. This last piece ensures that we can handle all of these cases with the same featurization code.
- Any objections to requiring numeric grades (i.e. the `"course_grade_numeric"` col) as inputs here, in addition to the raw grade? I could simplify the inputs and just recompute the numeric grade, since it's a …
=> [PDP] Finish grade feature generalization

.github/actions/setup-python-env/action.yml, .github/workflows/publish.yml
- bumps version of `uv` used in GH workflows ([release notes](https://github.com/astral-sh/uv/releases) if curious)
- enables publish package to PyPI GH workflow step, after adding necessary repo secret
This is a prerequisite to publishing a v0.1 of this package to PyPI.
- How strongly do folks feel about publishing to "test PyPI" before doing an official release? It's a helpful way to catch errors before you make a very public mistake, but not strictly necessary.
=> [CI] Update uv and enable PyPI publish step

src/student_success_tool/analysis/pdp/eda.py, tests/analysis/pdp/test_eda.py
- adds `compute_pairwise_associations()` function to `eda` module, which is a more generic equivalent to `DataFrame.corr()` that handles nominal-nominal and nominal-numeric column pairs in addition to the usual numeric-numeric
- adds unit tests for said function
I needed a way to compute associations for more data types, since PDP has so many string/categorical variables.
Nope!
=> [pdp] Add column associations EDA func

src/student_success_tool/analysis/pdp/dataops.py, tests/analysis/pdp/test_dataops.py
refactors how year/term values get masked in cleanup function, such that the input dataframe's dtypes are preserved; this function used to mangle dtypes, which was a pain point in the modeling dataset workflow
Just taking the time to smooth out some rough edges.
- Are the new functions logical equivalents of the old ones? They _should_ be, but `pandas` is tricksy 🤷‍♂️
=> Improve labeled dataset cleanup logic

src/student_success_tool/modeling/utils.py, tests/modeling/test_utils.py
adds functions (and unit tests) for common modeling-adjacent tasks: splitting datasets into exclusive subsets, and computing sample weights to deal with class imbalance
I've had to do this stuff "custom" for more than one school, but it's the same logic, so should be in the shared lib code.
Follows PR #40
Are there any other tasks like this to include?
=> [pdp] Extend modeling functionality

pyproject.toml, src/student_success_tool/assets/pdp/features_table.toml, src/student_success_tool/modeling/__init__.py, src/student_success_tool/modeling/inference.py, src/student_success_tool/modeling/utils.py, tests/modeling/test_inference.py, uv.lock
- adds `tomli` as optional project dependency (for PY3.10 only)
- adds "assets" directory, and within it, adds a "features table" toml file mapping PDP column names to human-friendly feature names (and, eventually, fuller descriptions)
- adds a utils func to load+parse features tables from disk
- adds feature values to inference topn feature display function (ported from https://github.com/datakind/student-success-intervention/pull/120) and also optional feature name mapping by way of a features table
PDP's internal feature column naming is a bit... technical. Advisors need more friendly naming to help them interpret model outputs correctly.
- Does this seem like a reasonable implementation?
- How do y'all feel about [TOML](https://toml.io/en/)? Personally I love it, and much prefer it …
=> [pdp] Map feature columns to human-friendly names

notebooks/pdp/02-prepare-modeling-dataset-TEMPLATE.py, pyproject.toml, src/student_success_tool/configs/__init__.py, src/student_success_tool/configs/load.py, src/student_success_tool/configs/schemas/pdp.py, uv.lock
- adds `pydantic` to build dependencies, used to define generic schemas analogously to `pandera` for datasets
- adds `configs` subpackage, with functionality for loading and validating project configuration from a toml file
- adds (first-draft) config schema for PDP projects
- adds example usage to template nb
This is a next step in standardizing / productionalizing PDP projects: most functionality being driven by a standard, human-friendly config file. We've long had something like this for model training in the private, school-specific repo, but this generalizes / improves upon the concept.
Builds on PR #43, which introduced toml for feature tables.
[Here](https://github.com/datakind/student-success-intervention/blob/c72f86311e7f088e044e37494a7bbae932007fd8/analysis/uscb/config.toml) is …
=> [pdp] Add project config functionality

notebooks/pdp/01-data-assessment-eda-TEMPLATE.py, notebooks/pdp/03-train-evaluate-model-TEMPLATE.py, src/student_success_tool/modeling/utils.py
- adds a partial model training+evaluation template notebook for pdp schools, with TODOs marked for where future work is needed
- fixes a bug in a modeling util function
Trying to extend the template school-agnostic pipeline further, from end to end.
Any objections to committing this in partial form, for future dev work?
=> Add (partial) train+eval model template nb

scripts/generate_synthetic_pdp_datasets.py, src/student_success_tool/generation/pdp/raw_cohort.py, src/student_success_tool/generation/pdp/raw_course.py, tests/generation/pdp/test_raw_cohort.py, tests/generation/pdp/test_raw_course.py
There's a cohort schema check that ensures there's a single institution for all the data, but the pdp generation script creates a new institution id per record (so data created using the script will fail the validation). This creates the institution id once and uses it for both cohort and course data.
- Generates institution id once in the parent script and then passes it down.
- Adds a test that uses the new field to pass the same value down to multiple cohorts/courses (this would fail without this change) for both cohort (which has the check) and course (which doesn't)
- Ranames test_raw_cohort_record to test_raw_course_record in test_raw_course.py (unrelated, looks like a copy paste error)
- Noticed this while running through the templates using the existing test data in the repo. Some …
=> Fix pdp gen failure from different institution ids

notebooks/pdp/config-TEMPLATE.toml, tests/configs/test_load.py, tests/fixtures/project_config.toml
- Adds a template config file to the notebooks dir, alongside other templates that rely on the config
- Adds a config test fixture file and adds a test for loading that config
Flagged in another PR — having a config template helps folks to use the template notebooks
- Any objections to including the config template inside the notebooks dir? Slightly awkward name-wise, but functionality-wise makes sense. We could consider renaming `notebooks` to something like, oh, `projects` or `templates`, if this really bugs you!
- Is anyone using this project config functionality in their school pipelines yet? (Besides me for USCB.) I'm thinking of changing the schema, but don't want to break anyone's pipelines. If the answer is yes, I'll push the schema change into the version after the next release …
=> [pdp] Add prelim template project config file

src/student_success_tool/modeling/inference.py, tests/modeling/test_inference.py
SHAP values need parallelization in order to scale for inference. Typically, predictions are generated for hundreds to thousands of students, so it is critical to have this functionality. Spark's repartition does not conserve row order, so the unique identifier needs to be attached every batch.
- Added "calculate_shap_values" to inference.py. 
- Added respective unit test within tests subdirectory.
- SHAP values are needed for interpretability. Proper scaling is required for inference.
- No specific questions
=> Update inference python file to include shap function

src/student_success_tool/modeling/inference.py, tests/modeling/test_inference.py
- auto-formats / lints / tidies up inference src and tests modules
- refactors single-batch shap values calculation logic into a separate function, and renames the spark udf that applies that batch func to chunks of a larger dataset
- adds a unit test for the single-batch shap values func
Prior art: PR #48 
Btw @vishpillai123 , I had started putting together an inference nb using code in this repo, but was waiting until I could chat with Daniel (Wednesday!) about how this is meant to work in practice, given confusion about the dbutils nb widgets and such.
=> Refactor SHAP inference functionality

notebooks/pdp/config-v2-TEMPLATE.toml, src/student_success_tool/configs/__init__.py, src/student_success_tool/configs/schemas/pdp_v2.py, tests/configs/schemas/test_pdp_v2.py
- adds a "v2" pdp project configuration schema, which differs from the previous iteration in structure and scope, plus additional validation and documentation
- adds an example template file for the v2 config
- adds a unit test to check that the schema is working correctly
Out-of-scope: Using this config in nbs. I tried that in another PR, but it got much too big.
This file is meant to record the full set of configuration options for a given school's pipeline in a way that's consolidated, human-readable, and not just hard-coded magic variables spread across multiple notebooks. It's especially useful when parameters must be shared and consistent across nbs; consolidating them here makes that task much easier and less error-prone.
The "v1" config was a WIP, but then a couple schools over in …
=> Improve pdp project config structure + functionality

notebooks/pdp/config-v2-TEMPLATE.toml, src/student_success_tool/configs/schemas/pdp_v2.py, tests/configs/schemas/test_pdp_v2.py
- changes `cfg.trained_model` into more flexible `cfg.models`, to allow for multiple named models trained using a given pipeline
- moves `min_prob_pos_label` from model to inference cfg, since that's _probably_ the only time in the process we'll need it; I'm not 100% sure on this tho, so I may move it back :)
- adds some descriptions to the config
Inspired by feedback in PR #56
=> [pdp] Tweak project config + template + test case

notebooks/pdp/01-data-assessment-eda-TEMPLATE.py
updates pdp data assessment template nb to leverage new project configs, fixes a few minor bugs, and adds more instruction in the middle and end wrt action items
trying to standardize the full pipeline, leverage project configs, and make everything work in both training and prediction runs
a subset of changes in PR #55, broken out for reviewability
=> [pdp] Refine data assessment template nb

src/student_success_tool/modeling/utils.py, tests/modeling/test_utils.py
I was running into issues with using this function and loading a TOML file from my local directory. 
- Added is_absolute() to resolve whether path is relative or absolute
- If referring to a path defined within module or an absolute path elsewhere, the function will retrieve the table. 
- I ran into an issue using this function for one of my schools (not PDP).
None
=> Modify load_feature_tables() function to allow for absolute & relative paths

notebooks/pdp/02-prepare-modeling-dataset-TEMPLATE.py
updates pdp prep modeling dataset template nb to leverage new project configs, work for both "train" and "predict" runs, and adds more instruction wrt action items
trying to standardize the full pipeline, leverage project configs, and make everything work in both training and prediction runs
a subset of changes in PR #55, broken out for reviewability
sibling to PR #59 
- I've moved feature selection **out** of this step of the pipeline. For multiple reasons (I can elaborate), this works better and more safely alongside model training. Any strong objections to this?
=> [pdp] Refine prep modeling dataset template nb

notebooks/pdp/03-train-evaluate-model-TEMPLATE.py, src/student_success_tool/configs/schemas/pdp_v2.py, src/student_success_tool/modeling/training.py
- updates pdp model train+evaluate template nb to leverage new project configs
- makes a couple col names in project config optional, with non-null defaults
- fixes a minor bug in automl wrapper function logic
trying to standardize the full pipeline, leverage project configs, and make everything work in both training and prediction runs
sibling to PRs #59 and #60 
- This nb is a little rougher than the preceding two because it hasn't _really_ been tested in actual pipelines yet. Do you see any serious problems or omissions? Happy to make this nb more robust here, at the same time as project config functionality is added in.
=> [pdp] Refine train+eval model template nb

notebooks/pdp/03-train-evaluate-model-TEMPLATE.py, notebooks/pdp/04-make-explain-predictions-TEMPLATE.py, src/student_success_tool/analysis/pdp/dataio.py, src/student_success_tool/modeling/utils.py
- adds pdp model predict + explain template nb consistent with preceding steps of the pipeline
- adds a utility function to load mlflow models from _the registry_
- adds a hacky plot to model eval nb
trying to standardize the full pipeline, leverage project configs, and make everything work in both training and prediction runs
final (and original intended) component of PR #55
please see the various TODOs embedded within the nb
=> [pdp] Add inference template nb

src/student_success_tool/analysis/pdp/dataio.py, tests/analysis/pdp/test_dataio.py
adds dataio functions to read raw pdp course+cohort datasets from file OR table, as a more general replacement for existing functions that only read these datasets from file
**note:** i'll remove the superseded functions in a later package release, to avoid breaking changes
based on plans for running prediction pipelines, it looks like we want to start reading raw datasets from tables rather than files. that's fine! the data _should_ be the same (modulo any weirdness in how things get formatted -- daniel is working on standardizing this afaik). these functions enable that process, while also supporting existing processes.
=> [pdp] add funcs to read raw datasets from table or file

src/student_success_tool/generation/pdp/raw_cohort.py
The previous code would occasionally return an error "day is out of range for month" when the randomly selected date was February 29th in a year that has a leap day (like 2024) (as February 29th of the following year would be invalid).
=> Adjust year logic to account for leap days

src/student_success_tool/dataio/pdp/raw_data.py
minimally invasive change: rename `"study_id"` column in raw data to standard `"student_guid"` column during dataio read, so that all downstream code/config works as-is for either case.
alternate possible approach: add a `study_id` field to the raw pdp data schemas, add a check to ensure both student guid and study id aren't present for a given dataframe, and then switch the value of the `student_id_col` field in the project config back and forth, as needed. feels clunky, but on the plus side it doesn't stealthily modify data.
for some reason pdp sends a different identifier column for students in different cases; i don't know any details, nobody has explained to me why this is the case. given the lack of understanding, i'm trying to make a minor change that easily lets us run existing …
=> [pdp] handle study_id / student_guid cols

src/student_success_tool/modeling/inference.py, tests/modeling/test_inference.py
uses new "Explanation" API under the hood when calculating SHAP values
related: https://github.com/datakind/student-success-tool/pull/96
- is it possible to return `Explanation` objects instead of constructing DataFrames, such that we could run this in parallel/distributed fashion and then... merge?... the explanations? specifically talking about this mess:
```python
shap_schema = StructType(
[StructField(cfg.student_id_col, StringType(), nullable=False)]
+ [StructField(col, FloatType(), nullable=False) for col in model_feature_names]
)
df_shap_values = (
spark.createDataFrame(
df_test.reindex(columns=model_feature_names + [cfg.student_id_col])
)  # noqa: F821
.repartition(sc.defaultParallelism)  # noqa: F821
.mapInPandas(
ft.partial(
modeling.inference.calculate_shap_values_spark_udf, …
```
=> [pdp] use new-style shap api

src/student_success_tool/pipeline_utils/gcsutils.py
There is a top-level directory in the output directory which we don't want to copy over (we just want the .png file in the top level directory).
Only copy the file when it's a .png file in the top-level directory.
=> Have gcsutils.py handle subdirs

pipelines/inference/pdp_inference/workflow_asset_bundle/resources/github_sourced_approval_pipeline, pipelines/tasks/approve_output/approve_output_task.py
Add a pipeline that approves output (e.g. publishes it to bucket as approved output and notifies user via email)
Add a pipeline (yml file) plus the task that is used in the pipeline to publish a given job's output and notify users via email.
=> Add approve output pipeline

.github/workflows/pre-release.yml, .github/workflows/style.yml, .github/workflows/type-check.yml
replaces old (compromised!) changed-files action with one that is not compromised
https://www.stepsecurity.io/blog/harden-runner-detection-tj-actions-changed-files-action-is-compromised
https://github.com/datakind/student-success-tool/pull/106
=> [ci] use new chg-file action that's not compromised

src/student_success_tool/utils/gcs.py
The current inference output file is a confusing name from databricks which gets propagated to the user. We should rename this to be more human readable
Save the csv with a readable name.
=> Update gcs.py inference output name

src/student_success_tool/modeling/bias_detection.py, tests/modeling/test_bias_detection.py
- Changed all naming of FNPR -> FNR.
- Clarified documentation and added references.
- The term FNPR or False Negative Parity Rate (what I've been using) is not commonly used and technically incorrect. We are actually looking at False Negative Rate Parity or FNR Parity, and specifically looking at the absolute percentage differences in FNR. 
- Parity can be either analyzed via a ratio with `FNR_subgroup1 / FNR_subgroup2`, or absolute percentage differences in FNR so `abs(FNR_subgroup1 - FNR_subgroup2)`. 
- This may seem like semantics (and it is), but we want to be accurate when reporting to institutions and in our model cards.
- Another consideration is why don't we look at FNR ratios instead of FNR differences when analyzing parity? 
- As an example, if we used a ratio and established a …
=> renaming FNPR to FNR for technical accuracy

pipelines/institution_id/config-TEMPLATE.toml, src/student_success_tool/configs/pdp.py, tests/configs/test_pdp.py
- reorders project config file so that classes follow in definition order
- restricts project config to defining a single ("best") model, rather than a mapping of models
- adds separate, fully-specified configs for each target, rather than a generic under-specified target config; also requires a new `type_` field, for model card parsing logic
- forbids extra params in project configs, just to be safe
- updates template config and tests
**TODO:** add checkpoint-specific configs in the same manner as targets
alternative to a subset of changes in PR #151
note: model configs are based on what's implemented in PR #149
- can this configuration be used to both populate model cards and execute pipelines without duplicate info, and still in a human-friendly form?
=> [pdp] more and better structured configs

pipelines/institution_id/00-data-assessment-TEMPLATE.py, pipelines/institution_id/04-register-model-create-card-TEMPLATE.ipynb, pyproject.toml, src/student_success_tool/reporting/README.md, src/student_success_tool/reporting/model_card/base.py, src/student_success_tool/reporting/sections/bias_sections.py, src/student_success_tool/reporting/template/styles/model_card.css, src/student_success_tool/reporting/utils/utils.py, tests/reporting/utils/test_utils.py, uv.lock
Followed after PR #154 is merged. For our model cards to be consumed, we need to convert our markdown file into pdf. There's several ways to do this, and I took the markdown -> HTML -> PDF route using CSS. 
For us to do any conversion into PDF, we need to use external packages. For our case, we used weasyprint and markdown, which is why there are new packages in pyproject.toml and uv.lock. 
Page 1 of what the PDF looks like is below. This is a solid start with what we need. Next steps will be looking for feedback from our team, leadership, and the research team (may be a follow-up PR to incorporate their feedback).
- Added weasyprint and markdown installs/imports
- Added CSS file to be used for all templates. 
- Added editing & conversion in template. After you create your markdown using …
=> add export of markdown to pdf for model cards

pipelines/institution_id/00-data-assessment-TEMPLATE.py, pipelines/institution_id/01-preprocess-data-TEMPLATE.py, pipelines/institution_id/02-train-model-TEMPLATE.py, pipelines/institution_id/03-make-predictions-TEMPLATE.py, pipelines/institution_id/04-register-model-create-card-TEMPLATE.py, src/student_success_tool/reporting/model_card/base.py
Updated templates to most recent version v0.3.1. Per our recent team alignment, we will be using these notebooks only interactively since PDP inference will be through shared pipeline in web app.
- Updated to v0.3.1.
- Removed outdated comments and code.
- Removed language around "it is okay to add to config later and hardcode now". 
- When users submit these notebooks for PR, we want to ensure all information is set in the config. 
- All school-specific info needs to be in the config. No parameters should be specified from the notebooks.
- Added saving of preprocessed, modeling, and advisor output datasets.
- Removed saving of validated datasets in EDA notebook since these aren't being used anywhere else. Validated datasets are created using our converter functions in the preprocess-data …
=> refactoring PDP templates to v0.3.1

src/student_success_tool/preprocessing/checkpoints/pdp.py, tests/preprocessing/checkpoints/test_pdp.py
We need the pre-cohort parameter for the `nth_student_term` func to work appropriately for schools who want an end of first year checkpoint (2 terms within a student's cohort)
=> changing func to include pre_cohort parameter

mlruns/0/meta.yaml, src/student_success_tool/preprocessing/targets/pdp/credits_earned.py, src/student_success_tool/preprocessing/targets/pdp/graduation.py, src/student_success_tool/preprocessing/targets/pdp/retention.py, tests/preprocessing/targets/pdp/test_graduation.py, tests/preprocessing/targets/pdp/test_retention.py
Remove NAs from the dataset if the target is incalculable.
Updated the compute target function for grad, retention, and credits earned to drop the NA target obs before returning. Updated tests to not expect NA values in the output.
When we compute the targets, previously, students with an NA value due to the fact they did not meet the eligibility criteria or have enough time left were included. Now, the code will drop these students that do not have a calculable target from the dataset. 
The NAs in the datasets were breaking graphing among other functions with this dataset.
none
=> Remove na target values

src/student_success_tool/modeling/registration.py, tests/modeling/test_registration.py
Our process does not prevent the same run/experiment becoming continuously registered which leads to unnecessary versioning. I've had 12 versions for one of my schools by just running the template notebook (same one with model cards). I believe @nm3224 has seen the same for one of her schools too.
- Using run-level tags which are saved in mlflow tracking server, and should be accessible from any initiated client.
- This is a fast way of tracking whether a run/experiment has been registered already.
- We can keep better track of our versions and not create many versions unnecessarily.
- No questions.
=> fix: prevent duplicate model registration using run-level tags

src/student_success_tool/reporting/model_card/base.py, src/student_success_tool/reporting/sections/custom/bias_sections.py, src/student_success_tool/reporting/sections/custom/evaluation_sections.py, src/student_success_tool/reporting/template/model-card-TEMPLATE.md, tests/reporting/model_card/test_model_card.py, tests/reporting/sections/custom/test_bias_sections.py
- Applicable for PDP & Custom: Feature selection's incomplete threshold (missing data threshold) was not formatted correctly in the base model card class, which affects both PDP and custom schools. Before `incomplete_threshold=0.2` would show up as 0.2% in the model card, so I fixed it to show up as 20%.
-  Applicable for PDP & Custom: If `split_col` doesn't exist in the training data then this breaks the build step, so adding a raising of Validation error in case it doesn't exist.
- Applicable to only Custom: Aliases are showing up correctly in most places, but it did not show up correctly in the "Disparities by Student Group" section which shows the flagged FNR plots. I realized this wasn't showing up because I didn't create the override! It was still using the base bias section, which …
=> fix/typo & aliases for custom schools in model cards
